#!/usr/bin/env lua
require("luarocks.loader")

local Sh = require("minilib.shell")
local Ut = require("minilib.util")

local dirs = {
	["~/.config"] = {},
	["~/.cache"] = {},
	["~/.theme"] = {},
	["~/.wlprs"] = {},
	["~/.local/bin"] = {},
}

local function setup_bell()
	Ut:exec([[
		pcnobell=$(grep -Po "^set bell-style none" /etc/inputrc)
		if [ "$pcnobell" = "" ]; then
			echo "disabling pc bell"
			echo "set bell-style none" | sudo tee /etc/inputrc
		else
			echo "not disabling pc bell"
		fi
	]])
end

local function setup_path() end

local function setup_dirs()
	for k, _ in pairs(dirs) do
		Sh.mkdir(k)
	end
end

-- TODO
local function setup_bins()
	for k, _ in pairs(bins) do
		Sh.ln(string.format("~/scripts/%s", k), string.format("~/.local/bin/%s", k))
	end
end

local function setup_touchpad_tap()
	Sh.sh([[
			sudo cp -vf misc/my/40*.conf /etc/X11/xorg.conf.d/
		]])
end

return {
	configure = function()
		setup_path()
		setup_dirs()
		setup_bell()
		setup_touchpad_tap()
	end,
	dependsOn = function()
		return true
	end,
	installer = function() end,
}
