#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	depends = {
		"sway",
	},
	configure = function()
		Shell.ln("$(pwd)/sway", "~/.config/sway")
	end,
	installer = function() end,
}
