#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/sway/my", "~/.config/sway")
	end,
	dependsOn = function()
		return Shell.file_exists({ "sway", "alacritty" })
	end,
	installer = function() end,
}
