#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.ln ("$(pwd)/picom/my", "~/.config/picom")
	end,
	dependsOn = function()
		Shell.file_exists("picom")
	end,
	installer = function()
	end
}
