#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/picom/my", "~/.config/picom")
	end,
	dependsOn = function()
		return Shell.file_exists("picom")
	end,
	installer = function() end,
}
