#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
		systemctl --user daemon-reload
		systemctl --user --now enable pipewire pipewire-pulse
		systemctl --user --now disable pulseaudio.service pulseaudio.socket
		systemctl --user mask pulseaudio
		]])
	end,
	dependsOn = function()
		Shell.file_exists("pipewire", "pipewire-pulse", "wireplumber")
	end,
	installer = function()
		-- deprecated
		--    Shell.sh [[
		-- sessf=$HOME/.config/pipewire-media-session/with-pulseaudio
		-- servd=$HOME/.config/systemd/user
		--
		-- if [ ! -f $sessf ] ; then
		-- 	echo "installing pulse session [with-pulseaudio] ..."
		-- 	if [ ! -d "$HOME/.config/pipewire-media-session" ]; then
		-- 		mkdir -p $HOME/.config/pipewire-media-session
		-- 	fi
		-- 	touch $sessf
		-- fi
		--
		-- if [ "$(ls $servd/pipewire-pulse.*)" = "" ]; then
		-- 	echo "installing pulse service ..."
		-- 	cp -v /usr/share/doc/pipewire/examples/systemd/user/pipewire-pulse.* $servd/
		-- fi
		-- ]]
		Shell.sh([[
			[ -d ~/.config/pipewire ] \
				|| mkdir ~/.config/pipewire
			[ -d ~/.config/pipewire/media-session.d ] \
				|| cp -rv /usr/share/pipewire/media-session.d/ ~/.config/pipewire/
		]])
	end,
}
