#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/mako", "~/.config/mako")
	end,
	depends = { "mako" },
	installer = function() end,
}
