#!/usr/bin/env lua

require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.ln ("$(pwd)/qutebrowser/my","~/.config/qutebrowser")
	end,
	dependsOn = function()
		Shell.file_exists ("qutebrowser")
	end,
	installer = function()
	end
}
