#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function() end,
	dependsOn = function()
		return Shell.file_exists("xmobar")
	end,
	installer = function()
		Shell.ln("$(pwd)/xmobar/my", "~/.config/xmobar")
	end,
}
