#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function() end,
	depends = { "xmobar" },
	installer = function()
		Shell.ln("$(pwd)/xmobar", "~/.config/xmobar")
	end,
}
