#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.ln ("$(pwd)/qtile/my","~/.config/qtile")
		--deprecated: doesnt work well
		--Shell.ln("$(pwd)/qtile/startqtile", "~/startqtile")
	end,
	dependsOn = function()
		Shell.file_exists ("qtile")
	end,
	installer = function()
	end
}
