#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/qtile/my", "~/.config/qtile")
	end,
	dependsOn = function()
		return Shell.file_exists("qtile")
	end,
	installer = function()
		Shell.sh([[
			cp $(pwd)/qtile/bin/* ${HOME}/.local/bin/
			]])
	end,
}
