#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.file_exists("dunst")
		Shell.ln("$(pwd)/dunst/my", "~/.config/dunst")
	end,
	dependsOn = function()
	end,
	installer = function()
	end
}
