#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function() end,
	dependsOn = function()
		Shell.file_exists("mediatomb")
	end,
	installer = function() end,
}
