#!/bin/sh 

if [ "$(lua -v)" == "" ]; then
  echo "install lua5.3, luarocks, curl and retry."
  exit -1
fi

lf=$(mktemp)
pk=conf-m
curl -kSL https://github.com/bucketsize/conf-m/archive/refs/heads/main.zip -o $lf
rm conf-m-main*
mv conf-m conf-m.$(date | md5sum | tr -d " -")

unzip $lf
mv conf-m-main conf-m

cd conf-m 
./setup 
