#!/bin/sh 

if [ "$(lua -v)" == "" ]; then
  echo "install lua5.3, luarocks, curl and retry."
  exit -1
fi

pk=conf-m
curl --progress-bar -SkO -L https://codeload.github.com/$pk/zip/refs/heads/main
rm conf-m-main*
mv conf-m conf-m.$(date | md5sum | tr -d " -")
unzip conf-m-main.zip

cd conf-m 
./setup 
