#!/usr/bin/env lua

require("luarocks.loader")
local Sh = require("minilib.shell")
local Ut = require("minilib.util")
local Pr = require("minilib.process")
local M = require("minilib.monad")
local dist_task = require("dist_task")

local config_group = require("config").groups

local function update_configs(path, subhbs)
	print("#update_configs:", path)
	Pr.pipe()
		.add(Sh.find(path, "%.t$"))
		.add(function(f)
			if f then
				local cwd = require("lfs").currentdir()
			end
			return f
		end)
		.add(Sh.read())
		.add(Sh.sed(subhbs))
		.add(function(fline)
			if fline == nil then
				return nil
			end
			fline.path = fline.path:gsub("%.t", "")
			return fline
		end)
		.add(Sh.write("./"))
		.run()
end
local function prepare_config(name)
	local subcfg = require("config")
	local subhbs = {}
	for i, v in pairs(subcfg) do
		subhbs["{" .. i .. "}"] = v
	end
	update_configs(string.format("%s/", name), subhbs)
end
local function prepare_configs()
	local subcfg = require("config")
	local subhbs = {}
	for i, v in pairs(subcfg) do
		subhbs["{" .. i .. "}"] = v
	end
	update_configs("./", subhbs)
end
local function handle_pkg_deps(e)
	local pkgs = M.List
		.of(e.depends)
		:filter(function(v)
			return type(v) == "string"
		end)
		:fmap(function(v)
			local r = dist_task.pkgalias(v)
			if r then
				return r
			else
				return v
			end
		end)
	return dist_task.pkginst(pkgs)
end
local function handle_github_deps(e)
	M.List
		.of(e.depends)
		:filter(function(v)
			if type(v) == "table" and v.method == "github" then
				return true
			end
			return false
		end)
		:fmap(function(v)
			local uri = string.format("curl -L https://raw.githubusercontent.com/%s/main/install | bash ", v.resource)
			print("#handle_github_deps", v.resource, "<-", uri)
			local s, er, ls = Sh.sh(uri)
			print("handle_github_deps", v, s, er, Ut.tos(ls))
			return s, er
		end)
	return "done"
end
local function setup_config(name)
	local e = dofile(string.format([[%s/setup]], name))
	if e.depends then
		handle_pkg_deps(e)
		handle_github_deps(e)
	end
	if e.installer then
		e.installer()
	end
	if e.configure then
		e.configure()
	end
	print(name, "Ok")
	return 0
end
local function setup_configs(name)
	for k, v in pairs(config_group[name]) do
		if not (v.state == "noi") then
			setup_config(k)
		end
	end
	return 0
end

if arg[1] == nil then
	print("#setup *")
	prepare_configs()
	setup_configs("sys")
	setup_configs("common")
	setup_configs("bspwm")
	setup_configs("sway")
else
	print("#setup " .. arg[1])
	prepare_config(arg[1])
	setup_config(arg[1])
end
