#!/usr/bin/env lua
require("luarocks.loader")

local Sh = require("minilib.shell")

return {
	configure = function() end,
	dependsOn = function()
		Sh.file_exists({ "lua", "luarocks" })
	end,
	installer = function()
		local arch = Sh.arch()

		Sh.exec([[
			if [ -d ~/minilib ]; then
				cd ~/minilib && git pull
			else
				git clone https://github.com/bucketsize/minilib.git ~/minilib
			fi
		]])

		Sh.exec(string.format(
			[[
		LIBDIR=/usr/lib/%s-linux-gnu
		cd ~/minilib && luarocks make --local CRYPTO_LIBDIR=$LIBDIR OPENSSL_LIBDIR=$LIBDIR
		]],
			arch
		))
	end,
}
