#!/usr/bin/env lua
require("luarocks.loader")

local Sh = require("minilib.shell")

return {
	configure = function()
		Sh.ln("$(pwd)/mangohud", "~/.config/MangoHud")
	end,
	depends = {
		"mangohud",
	},
	installer = function() end,
}
