#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/qt5ct", "~/.config/qt5ct")
	end,
	dependsOn = function()
		return Shell.file_exists("qt5ct")
	end,
	installer = function() end,
}
