#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.ln ("$(pwd)/qt5ct/my","~/.config/qt5ct")
	end,
	dependsOn = function()
		Shell.file_exists ("qt5ct")
	end,
	installer = function()
	end
}
