#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function() end,
	dependsOn = function()
		return true
	end,
	installer = function()
		Shell.sh([[
      sudo mkdir -p /usr/share/xsessions
      sudo cp $(pwd)/xinit/my/*.desktop /usr/share/xsessions
    ]])
	end,
}
