#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function() end,
	depends = {},
	installer = function()
		Shell.sh([[
      sudo mkdir -p /usr/share/xsessions
      sudo cp $(pwd)/xinit/*.desktop /usr/share/xsessions
    ]])
	end,
}
