#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")
local Util = require("minilib.util")

return {
	configure = function() end,
	dependsOn = function()
		return true
	end,
	installer = function() end,
}
