#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/swhkd/my", "~/.config/swhkd")
	end,
	dependsOn = function()
		return Shell.file_exists("swhkd")
	end,
	installer = function() end,
}
