#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/swhkd/my", "~/.config/swhkd")
	end,
	depends = { "swhkd" },
	installer = function() end,
}
