#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/lxpanel", "$HOME/.config/lxpanel")
	end,
	depends = { "lxpanel" },
	installer = function() end,
}
