#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	depends = { "lua", "luarocks" },
	configure = function()
		-- Shell.ln("$(pwd)/autostart/autostartd", "~/.local/bin/autostartd")
		-- Shell.mkdir("~/.config/systemd/user")
		-- Shell.sh([[
		-- 	ln -sfv $(pwd)/autostart/autostart.service ~/.config/systemd/user/autostart.service
		--     systemctl --user daemon-reload
		--     systemctl --user enable autostart.service
		--     ]])

		Shell.ln("$(pwd)/autostart", "~/.config/autostart")
		-- Shell.sh("chmod -v +x $(pwd)/autostart/autostart")
	end,
}
