#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	dependsOn = function()
		Shell.file_exists("lua", "luarocks")
	end,
	configure = function()
		-- Shell.ln("$(pwd)/autostart/my/autostartd", "~/.local/bin/autostartd")
		-- Shell.mkdir("~/.config/systemd/user")
		-- Shell.sh([[
		-- 	ln -sfv $(pwd)/autostart/my/autostart.service ~/.config/systemd/user/autostart.service
		--     systemctl --user daemon-reload
		--     systemctl --user enable autostart.service
		--     ]])

		Shell.ln("$(pwd)/autostart/my", "~/.config/autostart")
		-- Shell.sh("chmod -v +x $(pwd)/autostart/my/autostart")
	end,
}
