#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")
local Util = require("minilib.util")

return {
	configure = function()
		Shell.exec([[
			sudo timedatectl set-timezone Asia/Kolkata
		]])
	end,
	dependsOn = function()
		return Shell.file_exists("timedatectl")
	end,
	installer = function() end,
}
