#!/usr/bin/env lua
require("luarocks.loader")

local Sh = require("minilib.shell")

return {
	configure = function() end,
	depends = { "modprobe" },
	installer = function()
		Sh.sh("sudo cp -v $(pwd)/modprobe.d/* /etc/modprobe.d/")
	end,
}
