#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")
local Util = require("minilib.util")

return {
	configure = function()
		Shell.ln("$(pwd)/vim/vimrc", "~/.vimrc")
	end,
	depends = { "vim" },
	installer = function() end,
}
