#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/bspwm/my", "~/.config/bspwm")
	end,
	dependsOn = function()
		return Shell.file_exists({
			"bspwm",
			"sxhkd",
			"feh",
			"lxpolkit",
			"tint2",
			"picom",
			"dunst",
			"ictl",
			"m360",
			"lemonbar",
		})
	end,
	installer = function() end,
}
