#!/usr/bin/env lua
require "luarocks.loader"

local Sh = require('minilib.shell')

return {
	configure = function()
		Sh.ln("$(pwd)/Xresources/my","~/.config/xresources.d")
		Sh.ln("$(pwd)/Xresources/my/Xresources","~/.Xresources")
		Sh.sh[[
      sudo cp -vf misc/my/40*.conf /etc/X11/xorg.conf.d/
    ]]
	end,
	dependsOn = function()
		return Sh.file_exists({"xrdb"})
	end,
	installer = function()
	end
}
