#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util  = require('minilib.util')

return {
	configure = function()
		Shell.ln("$(pwd)/Xresources/my","~/.config/xresources.d")
		Shell.ln("$(pwd)/Xresources/my/Xresources","~/.Xresources")
	end,
	dependsOn = function()
		return Shell.file_exists("xrdb")
	end,
	installer = function()
	end
}
