#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
			sudo cp -vf sysctl.d/*.conf /etc/sysctl.d/
			sudo sysctl -p
		]])
	end,
	depends = {
		"sysctl",
	},
	installer = function() end,
}
