#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')

return {
	configure = function()
		Shell.sh([[
		sudo cp -vf greetd/my/* /etc/greetd/
		]])
	end,
	dependsOn = function()
	end,
	installer = function()
	end
}
