#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
    mkdir /etc/greetd
		sudo cp -vf greetd/* /etc/greetd/
    sudo useradd -M -G video greeter
    sudo chmod -R go+r /etc/greetd/
     
    # when ready, execute
    sudo systemctk disable display-manager
    sudo systemctl enable greetd
		]])
	end,
	depends = { "greetd" },
	installer = function() end,
}
