#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/dunst", "~/.config/dunst")
	end,
	depends = { "dunst" },
	installer = function() end,
}
