#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/dunst/my", "~/.config/dunst")
	end,
	dependsOn = function()
		Shell.file_exists("dunst")
	end,
	installer = function() end,
}
