#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/sxhkd/my", "~/.config/sxhkd")
	end,
	depends = { "sxhkd" },
	installer = function() end,
}
