#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.ln ("$(pwd)/sxhkd/my","~/.config/sxhkd")
	end,
	dependsOn = function()
		Shell.file_exists ("sxhkd")
	end,
	installer = function()
	end
}
