#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	dependsOn = function()
		return Shell.file_exists("compton")
	end,
	configure = function()
		Shell.ln("~/scripts/config/compton/my", "~/.config/compton")
	end,
}
