#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	dependsOn = { "compton" },
	configure = function()
		Shell.ln("~/scripts/config/compton", "~/.config/compton")
	end,
}
