#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	dependsOn = function()
		Shell.file_exists("compton")
	end,
	configure = function()
		Shell.ln ("~/scripts/config/compton/my", "~/.config/compton")
	end
}
