#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	depends = {
		"waybar",
	},
	configure = function()
		Shell.ln("$(pwd)/waybar/my", "~/.config/waybar")
	end,
	installer = function()
		Shell.sh([[
			cp $(pwd)/waybar/bin/* ${HOME}/.local/bin/
			]])
	end,
}
