#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
	end,
	dependsOn = function()
		Shell.file_exists({"git", "make", "urxvt", "xrandr", "fzy", "wmctrl", "pactl", "feh"})
	end,
	installer = function()
		Shell.github_fetch("bucketsize", "frmad")
		Shell.sh(string.format([[
			LIBDIR=/usr/lib/%s-linux-gnu
			cd ~/frmad && luarocks make --local CRYPTO_LIBDIR=$LIBDIR OPENSSL_LIBDIR=$LIBDIR 
			if [ -d ~/.config/frmad ]; then
				echo "[~/.config/frmad] already present"
			else
				mkdir -p ~/.config/frmad
				cp ~/scripts/config/frmad/my/config ~/.config/frmad/
			fi
		]], Shell.arch()))
	end
}
