#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
			[ -d ~/.config/mxctl ] \
				|| mkdir -v -p ~/.config/mxctl
			[ -f ~/.config/mxctl/config ] \
				|| cp -v $(pwd)/mxctl/config ~/.config/mxctl/
		]])
	end,
	depends = { "git", "make", "xrandr", "fzf", "wmctrl", "pactl", "feh", "wget" },
	installer = function()
		Shell.github_fetch("bucketsize", "frmad")
		Shell.sh(string.format(
			[[
			export CRYPTO_INCDIR=/usr/include	
			LIBDIR=/usr/lib/%s-linux-gnu
 			CRYPTO_LIBDIR=$LIBDIR
 			OPENSSL_LIBDIR=$LIBDIR 
			cd ~/frmad && luarocks make --local
		]],
			Shell.arch()
		))
	end,
}
