#!/usr/bin/env lua
require "luarocks.loader"

local Sh = require('minilib.shell')
local Ut = require('minilib.util')


return {
	configure = function()
		Sh.ln("$(pwd)/triggerhappy/my", "~/.config/triggerhappy")

		if Sh.path_exists("/usr/sbin/thd")  -- debian non std path for exe
			and (not Sh.path_exists("/usr/bin/thd"))
			and (not Sh.path_exists(Sh.HOME .. "/.local/bin/thd"))
			then
				Sh.ln("/usr/sbin/thd", Sh.HOME .. "/.local/bin/thd")
		end

		if not Ut:haz(Sh.groups(), "input") then
			print ("add user to input group ...")
			Sh.sh([[
				sudo usermod $USER -a -G input
			]])
			print ("relogin for it to work!")
		end
	end,
	dependsOn = function()
		Sh.file_exists("thd")
	end,
	installer = function()
	end
}
