#!/usr/bin/env lua
require("luarocks.loader")

local Sh = require("minilib.shell")

return {
	configure = function()
		Sh.ln("$(pwd)/fontconfig/my", "~/.config/fontconfig")
	end,
	depends = { "fc-list" },
	installer = function() end,
}
