#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.mkdir("~/.config/nvim")
		Shell.ln("$(pwd)/nvim/my/init.lua", "~/.config/nvim/init.lua")
	end,
	dependsOn = function()
		Shell.file_exists("nvim")
	end,
	installer = function() end,
}
