#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.mkdir("~/.config/nvim")
		Shell.ln("$(pwd)/nvim/my", "~/.config/nvim")
    if Shell.path_exists("~/.var/app/io.neovim.nvim/config/user-dirs.dirs")
        && not Shell.path_exists("~/.var/app/io.neovim.nvim/config/nvim/init.lua") then
      Shell.ln("~/.config/nvim", "~/.var/app/io.neovim.nvim/config/nvim")
    end
	end,
	dependsOn = function()
		return Shell.file_exists("nvim")
            or Shell.path_exists("~/.var/app/io.neovim.nvim/config/user-dirs.dirs"), "nvim"
	end,
	installer = function() end,
}
