#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/hypr/my", "~/.config/hypr")
	end,
	dependsOn = function()
		return Shell.file_exists({ "Hyprland", "hyprctl" })
	end,
	installer = function()
		Shell.sh([[
			cp $(pwd)/hypr/bin/* ${HOME}/.local/bin/
			]])
	end,
}
