#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/hypr", "~/.config/hypr")
	end,
	depends = { "Hyprland", "hyprctl" },
	installer = function()
		Shell.sh([[
			cp $(pwd)/hypr/bin/* ${HOME}/.local/bin/
			]])
	end,
}
