#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.ln ("$(pwd)/mpv/my", "~/.config/mpv")
	end,
	dependsOn = function()
		Shell.file_exists ("mpv")
	end,
	installer = function()
	end
}
