#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/mpv", "~/.config/mpv")
	end,
	depends = { "mpv" },
	installer = function() end,
}
