#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')

return {
	configure = function()
		if not Shell.path_exists("~/.local/bin/stterm") then
			Shell.sh([[chmod +x $(pwd)/st/bin/stterm]])
		end
	end,
	dependsOn = function()
	end,
	installer = function()
		Shell.sh ([[
			cp $(pwd)/st/bin/* ${HOME}/.local/bin/
			]])
	end
}

