#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
			sudo cp -vf thermald/* /etc/thermald/
    ]])
		print([[
      # NOTE
      On some systems, thermald.service starts with --adaptive flag.
      This does not honor xml configs and may not work properly. 

      Edit
        /lib/systemd/system/thermald.service
      Then
        systemctl daemon-reload
        systemctl restart thermald 
    ]])
	end,
	depends = { "thermald" },
	installer = function() end,
}
