#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
		[ -d /etc/systemd/logind.conf.d ] || sudo mkdir /etc/systemd/logind.conf.d	
		sudo cp -vf logind.d/my/*.conf /etc/systemd/logind.conf.d/
		]])
	end,
	dependsOn = function()
		return Shell.file_exists("udevadm")
	end,
	installer = function() end,
}
