#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.ln("$(pwd)/conky/line", "~/.config/conky")
		Shell.sh("chmod +x $(pwd)/conky/line/conky-lemonbar.sh")
	end,
	dependsOn = function()
		Shell.file_exists("conky")
	end
}
