#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/conky/line", "~/.config/conky")
		Shell.sh("chmod +x $(pwd)/conky/line/conky-lemonbar.sh")
	end,
	depends = { "conky" },
}
