#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
			[ -d ~/.config/m360 ] || mkdir -v -p ~/.config/m360
			[ -f ~/.config/m360/config ] || cp -v $(pwd)/m360/my/config ~/.config/m360/
		]])
	end,
	dependsOn = function()
		return Shell.file_exists({ "python3", "pactl", "curl" })
	end,
	installer = function() end,
}
