#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
			[ -d ~/.config/m360 ] || mkdir -v -p ~/.config/m360
			[ -f ~/.config/m360/config.json ] || cp -v $(pwd)/m360/config.json ~/.config/m360/
		]])
	end,
	depends = { "python3", "pactl", "curl" },
	installer = function() end,
}
