#!/usr/bin/env lua

require("luarocks.loader")

local Sh = require("minilib.shell")
local Tr = require("minilib.timer")

Sh.sh([[
xrdb -merge ~/.Xresources
xhost +
xsetroot -cursor_name left_ptr
setxkbmap us

# dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
dbus-launch --sh-syntax --exit-with-session
dbus-update-activation-environment --systemd --all
]])
Tr.sleep(1)

-- needed on VBox for proper display scaling
Sh.forkonce("VBoxClient", "--vmsvga")
Sh.forkonce("VBoxClient", "--clipboard")

Sh.forkonce("mpd")
Sh.forkonce("dunst")

-- Sh.forkonce("alacritty")
Sh.sh("mxctl.control getwallpaper")

-- sys key binder
Sh.forkonce("thd", "--triggers ~/.config/triggerhappy/th.conf --deviceglob /dev/input/event*")

-- swhkd has some permission problems with regular user
-- hence going to use thd for now
-- Sh.sh("(swhks &) && pkexec swhkd -c ~/.config/sxhkd/sharedrc")

-- get wallpaper and symlink for next login
Sh.sh("mxctl.control getwallpaper")

-- Sh.forkonce("xss-lock", "gtklock")
