#!/bin/sh

xrdb -merge ~/.Xresources
xhost +
xsetroot -cursor_name left_ptr
setxkbmap us

# dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
dbus-launch --sh-syntax --exit-with-session
dbus-update-activation-environment --systemd --all

sleep 1

# needed on VBox for proper display scaling
VBoxClient --vmsvga
VBoxClient --clipboard

mpd &
mako &

#ictl setup_video
#ictl applywallpaper

#tint2 &

if [[ "$(hostnamectl hostname)" =~ "fuhrer" ]]; then
	steam steam://open/bigpicturesteam
fi
