#!/bin/sh

. ~/.profile
xrdb -merge ~/.Xresources
xhost +
xsetroot -cursor_name left_ptr
setxkbmap us

# dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
dbus-launch --sh-syntax --exit-with-session
dbus-update-activation-environment --systemd --all

ictl applywallpaper
sxhkd -c ~/.config/sxhkd/bspwmrc ~/.config/sxhkd/sharedrc &
dunst &
lxpolkit &

run_once m360 >/dev/null &

notify-send "openbox autostart done"
exec /usr/games/steam steam://open/bigpicture
