#!/bin/sh

set -x

echo ">> $(date)"

xrdb -merge ~/.Xresources
xhost +
xsetroot -cursor_name left_ptr
setxkbmap us

# dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
dbus-launch --sh-syntax --exit-with-session
dbus-update-activation-environment --systemd --all

sleep 1

# needed on VBox for proper display scaling
VBoxClient --vmsvga
VBoxClient --clipboard

# sys key binder
# thd  --triggers ~/.config/triggerhappy/th.conf --deviceglob /dev/input/event*
sxhkd -c ~/.config/sxhkd/winrc ~/.config/sxhkd/sharedrc &
lxpolkit &
picom &
dunst &
mpd &

xrandr --output eDP-1 --mode 1280x720 --rotate normal --pos 0x0
ictl applywallpaper

tint2 &
parcellite &

m360 1 >/dev/null &
sleep 2 && (tail -f /tmp/m360.lemonbar.out.${USER} | lemonbar &) # xmobar or conky or lemonbar

if [[ "$(hostnamectl hostname)" =~ "fuhrer" ]]; then
	steam steam://open/bigpicturesteam
fi

echo "<< $(date)"
# xss-lock gtklock
