#!/bin/sh

xrdb -merge ~/.Xresources
xhost +
xsetroot -cursor_name left_ptr
setxkbmap us

# dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
dbus-launch --sh-syntax --exit-with-session
dbus-update-activation-environment --systemd --all

sleep 1

# needed on VBox for proper display scaling
VBoxClient --vmsvga
VBoxClient --clipboard

# sys key binder
# thd  --triggers ~/.config/triggerhappy/th.conf --deviceglob /dev/input/event*
sxhkd -c ~/.config/sxhkd/bspwmrc ~/.config/sxhkd/sharedrc &
mpd &
picom &
dunst &
tint2 &
parcellite &

ictl setup_video
ictl applywallpaper

m360 1 >/dev/null &
tail -f /tmp/m360.lemonbar.out.${USER} | lemonbar & # xmobar or conky or lemonbar

if [[ "$(hostnamectl hostname)" =~ "fuhrer" ]]; then
	steam steam://open/bigpicturesteam
fi

# xss-lock gtklock
