#!/bin/sh

xrdb -merge ~/.Xresources
xhost +
xsetroot -cursor_name left_ptr
setxkbmap us

# dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
dbus-launch --sh-syntax --exit-with-session
dbus-update-activation-environment --systemd --all

sleep 1

# needed on VBox for proper display scaling
VBoxClient --vmsvga
VBoxClient --clipboard

# sys key binder
# thd  --triggers ~/.config/triggerhappy/th.conf --deviceglob /dev/input/event*
sxhkd -c ~/.config/sxhkd/bspwmrc ~/.config/sxhkd/sharedrc &
mpd &
picom &
dunst &
tint2 &
parcellite &

#  urxvtd -q -o -f
#  Ut.sleep(1)
#  urxvtc  -- to be safe
#  stterm
#  alacritty

ictl setup_video
ictl applywallpaper

p=/tmp/frmad.lemonbar.out.${USER}
[ -p $p] || mkfifo $p

frmad.daemon &
sleep 1

tail -f /tmp/frmad.lemonbar.out.${USER} | lemonbar # xmobar or conky or lemonbar

# xss-lock gtklock
