#!/usr/bin/env lua
require "luarocks.loader"

local Sh = require('minilib.shell')
local Ut = require('minilib.util')
local Pr = require('minilib.process')

return {
	configure = function()
		Pr.pipe()
			.add(Sh.exec("find -L ~/.mozilla/ ~/snap -name \"xulstore.json\" | grep -v backup"))
			.add(Sh.echo())
			.add(function (x)
				if x then
					local f, p = Sh.split_path(x)
					Sh.cp ("$(pwd)/firefox/my/user.js", p)
				end
			end)
			.run()
	end,
	dependsOn = function()
		Sh.file_exists("firefox")
	end,
	installer = function()
	end
}
