#!/usr/bin/env lua
require("luarocks.loader")

local Sh = require("minilib.shell")
local Pr = require("minilib.process")

return {
	configure = function()
		Pr.pipe()
			.add(Sh.exec('find -L ~/.mozilla/ ~/snap -name "xulstore.json" | grep -v backup'))
			.add(Sh.echo())
			.add(function(x)
				if x then
					local _, p = Sh.split_path(x)
					Sh.cp("$(pwd)/firefox/my/user.js", p)
				end
			end)
			.run()
	end,
	depends = { "firefox" },
	installer = function() end,
}
