#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.sh([[
			sudo cp -vf tlp.d/my/*.conf /etc/tlp.d/
			sudo tlp start
		]])
	end,
	dependsOn = function()
	end,
	installer = function()
	end
}
