#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
			sudo cp -vf tlp.d/my/*.conf /etc/tlp.d/
			sudo systemctl restart tlp
		]])
	end,
	depends = { "tlp" },
	installer = function() end,
}
