#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
			sudo cp -vf tlp.d/my/*.conf /etc/tlp.d/
			sudo tlp start
		]])
	end,
	dependsOn = function()
		return Shell.file_exists("tlp")
	end,
	installer = function() end,
}
