#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
			[ -d ~/.config/ictl ] || mkdir -v -p ~/.config/ictl
			[ -f ~/.config/ictl/config.json ] || cp -v $(pwd)/ictl/config.json ~/.config/ictl/
		]])
	end,
	depends = {
		"xterm",
		"xrandr",
		"fzf",
		"wmctrl",
		"pactl",
		"feh",
		"curl",
	},
	installer = function()
		Shell.ln("$(pwd)/ictl/wallpaper-1.jpg", "~/Pictures/wallpaper-1.jpg")
	end,
}
