#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	dependsOn = function()
		return Shell.file_exists({ "chromium" })
	end,
	configure = function()
		-- note; only works on arch linux
		Shell.ln("$(pwd)/chromium/my/chromium-flags.conf", "~/.config/chromium-flags.conf")

		-- other distros; custom entrypoint
		Shell.mkdir("~/.local/share/applications")
		Shell.ln("$(pwd)/chromium/my/chromium-accel.desktop", "~/.local/share/applications/chromium-accel.desktop")
	end,
}
