#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.mkdir("~/.mpd")
		Shell.ln("$(pwd)/mpd/my", "~/.config/mpd")

		-- going to disable automatic root start of mpd
		Shell.sh("sudo systemctl disable mpd")
	end,
	dependsOn = function()
		Shell.file_exists({ "mpd", "mpc" })
	end,
	installer = function() end,
}
