#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.mkdir("~/.mpd")
		Shell.ln("$(pwd)/mpd", "~/.config/mpd")

		-- going to disable automatic root start of mpd
		Shell.sh("sudo systemctl disable mpd")
	end,
	depends = { "mpd", "mpc" },
	installer = function() end,
}
