#!/usr/bin/env lua
require("luarocks.loader")

local Sh = require("minilib.shell")

return {
	configure = function()
		Sh.ln("$(pwd)/tmux", "$HOME/.config/tmux")
	end,
	depends = { "tmux" },

	installer = function() end,
}
