#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/openbox/my", "$HOME/.config/openbox")
	end,
	dependsOn = function()
		return Shell.file_exists("openbox", "obconf")
	end,
	installer = function()
		Shell.sh([[
			cp $(pwd)/openbox/bin/* ${HOME}/.local/bin/
			]])

		-- theme
		Shell.mkdir("~/.themes")

		-- TODO : use release tar.gz
		Shell.sh([[
			cd ~/.themes
			if [ ! -d nord-openbox-theme ]; then 
				git clone https://gitlab.com/the-zero885/nord-openbox-theme.git
			fi
			if [ ! -d arc-openbox ]; then 
				git clone https://github.com/dglava/arc-openbox.git
				cp -a arc-openbox/* ./
			fi
			]])
	end,
}
