#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.sh([[
		[ -d /etc/systemd/logind.conf.d ] || sudo mkdir /etc/systemd/logind.conf.d	
		sudo cp -vf logind.d/my/*.conf /etc/systemd/logind.conf.d/
		]])
	end,
	dependsOn = function()
	end,
	installer = function()
	end
}
