#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
		[ -d /etc/udev/rules.d ] || sudo mkdir /etc/udev/rules.d	
		sudo cp -vf rules.d/* /etc/udev/rules.d/
		]])
	end,
	dependsOn = function()
		return Shell.file_exists("udevadm")
	end,
	installer = function() end,
}
