#!/usr/bin/env lua

require "luarocks.loader"

local Sh = require("minilib.shell")
local Ut = require("minilib.util")

function autostart()
	Sh.sh([[
		xrdb -merge ~/.Xresources
		xhost +
		xsetroot -cursor_name left_ptr
		setxkbmap us
    
		# dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
		dbus-launch --sh-syntax --exit-with-session
		dbus-update-activation-environment --systemd --all
	]])
    
	-- needed on VBox for proper display scaling
	Sh.forkonce("VBoxClient --vmsvga")

    -- sys key binder
	Sh.forkonce("thd --triggers", "~/.config/triggerhappy/th.conf --deviceglob /dev/input/event*")
	Sh.forkonce("mpd")
    Sh.forkonce("dunst")
    Sh.forkonce("lxqt-policykit-agent")
    Sh.forkonce("lxqt-powermanagement")
    Sh.forkonce("VBoxClient --clipboard")
end

return autostart
