#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.mkdir("~/.local/bin")

		Shell.ln("$(pwd)/lspd/my/lspd-ocaml", "~/.local/bin/lspd-ocaml")
		Shell.ln("$(pwd)/lspd/my/lspd-java", "~/.local/bin/lspd-java")
	end,
	depends = {},
	installer = function() end,
}
