[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# switch vt
switch = true

# The default session, also known as the greeter.
[default_session]
user = "greeter"
command = "agreety --cmd xorg-openbox"
# command = "cage -s -- gtkgreet"


[initial_session]
user = "jb"
command = "xorg-openbox"

[general]
source_profile = true

