#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
	end,
	dependsOn = function()
		Shell.file_exists({"git", "make", "urxvt", "xrandr", "fzy", "wmctrl", "pactl", "feh"})
	end,
	installer = function()
		Shell.github_fetch("bucketsize", "mxctl")
		Shell.sh(string.format([[
			LIBDIR=/usr/lib/%s-linux-gnu
			cd ~/mxctl && luarocks make --local CRYPTO_LIBDIR=$LIBDIR OPENSSL_LIBDIR=$LIBDIR 
			if [ -d ~/.config/mxctl ]; then
				echo "[~/.config/mxctl] already present"
			else
				mkdir -p ~/.config/mxctl
				cp ~/scripts/config/mxctl/my/config ~/.config/mxctl/
			fi
		]], Shell.arch()))
	end
}
