#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.sh([[
			[ -d ~/.config/mxctl ] \
				|| mkdir -v -p ~/.config/mxctl
			[ -f ~/.config/mxctl/config ] \
				|| cp -v $(pwd)/mxctl/my/config ~/.config/mxctl/
		]])
	end,
	dependsOn = function()
		Shell.file_exists({ "git", "make", "urxvt", "xrandr", "fzy", "wmctrl", "pactl", "feh" })
	end,
	installer = function()
		Shell.github_fetch("bucketsize", "mxctl")
		Shell.sh(string.format(
			[[
			export CRYPTO_INCDIR=/usr/include	
			LIBDIR=/usr/lib/%s-linux-gnu
 			CRYPTO_LIBDIR=$LIBDIR
 			OPENSSL_LIBDIR=$LIBDIR 
			cd ~/mxctl && luarocks make --local
		]],
			Shell.arch()
		))
	end,
}
