#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/foot", "~/.config/foot")
	end,
	depends = { "foot" },
	installer = function() end,
}
