#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.ln ("$(pwd)/foot/my", "~/.config/foot")
	end,
	dependsOn = function()
		Shell.file_exists("foot")
	end,
	installer = function()
	end
}
