#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

return {
	configure = function()
		Shell.ln("$(pwd)/weston/my/weston.ini", "~/.config/weston.ini")
		Shell.ln("$(pwd)/weston/startweston", "~/startweston")
	end,
	dependsOn = function()
		Shell.file_exists("weston")
		Shell.file_exists("foot")

	end,
	installer = function()
	end
}
