#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/weston/my/weston.ini", "~/.config/weston.ini")
	end,
	dependsOn = function()
		return Shell.file_exists({ "weston", "foot" })
	end,
	installer = function()
		Shell.sh([[
			cp $(pwd)/weston/bin/* ${HOME}/.local/bin/
			]])
	end,
}
