#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/weston/weston.ini", "~/.config/weston.ini")
	end,
	depends = { "weston", "foot" },
	installer = function()
		Shell.sh([[
			cp $(pwd)/weston/bin/* ${HOME}/.local/bin/
			]])
	end,
}
