#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/tint2/dashy", "~/.config/tint2")
	end,
	depends = { "tint2" },
	installer = function() end,
}
