#!/usr/bin/env lua
require("luarocks.loader")

local Shell = require("minilib.shell")

return {
	configure = function()
		Shell.ln("$(pwd)/tint2/dashy", "~/.config/tint2")
	end,
	dependsOn = function()
		Shell.file_exists("tint2")
	end,
	installer = function() end,
}
